name: Test Upload To Release

on:
    push:
        branches: [main]
    workflow_dispatch:

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Run Upload To Release Action
              id: upload
              uses: levminer/upload-to-release@test
              with:
                  files: "package.json, package-lock.json"
