name: Test Upload To Release

on: [push, pull_request]

permissions:
    contents: write

jobs:
    test:
        runs-on: ubuntu-latest
        env:
            GH_TOKEN: ${{ github.token }}
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Run Upload To Release Action
              id: upload
              uses: levminer/upload-to-release@test
              with:
                  linux-files: "test/file.txt, test/file-%v.txt"
                  overwrite: "true"
